In [117]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [118]:
# importing the breast cancer dataset from sklearn

from sklearn import datasets
dataset = datasets.load_breast_cancer()

In [119]:
# getting the shapes of the arrays

dataset['feature_names'].shape, dataset['data'].shape, dataset['target'].shape

((30,), (569, 30), (569,))

In [120]:
# separating the data, feature names and target label into different arrays

data_array = dataset['data']
feature_names = dataset['feature_names']
target_array = dataset['target']

In [121]:
data_array[:5],target_array[:5]

(array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
         3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
         8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
         3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
         1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, 1.326e+03, 8.474e-02, 7.864e-02,
         8.690e-02, 7.017e-02, 1.812e-01, 5.667e-02, 5.435e-01, 7.339e-01,
         3.398e+00, 7.408e+01, 5.225e-03, 1.308e-02, 1.860e-02, 1.340e-02,
         1.389e-02, 3.532e-03, 2.499e+01, 2.341e+01, 1.588e+02, 1.956e+03,
         1.238e-01, 1.866e-01, 2.416e-01, 1.860e-01, 2.750e-01, 8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, 1.203e+03, 1.096e-01, 1.599e-01,
         1.974e-01, 1.279e-01, 2.069e-01, 5.999e-02, 7.456e-01, 7.869e-01,
         4.585e+00, 9.403e+01, 6.150e-03, 4.006e-02, 3.832e-02, 2.058e-02,
         2.250e-02, 4.5

In [122]:
# concatenating the data array and target array to form the pandas dataframe

new = np.concatenate((data_array.reshape(len(data_array), data_array.shape[1]), target_array.reshape(len(target_array), 1)), 1)
feature_names = np.append(feature_names, 'Target')
feature_names = feature_names[:31]


framed_data = pd.DataFrame(new, columns=feature_names)
framed_data.head()

mean radius  mean texture  ...  worst fractal dimension  Target
0        17.99         10.38  ...                  0.11890     0.0
1        20.57         17.77  ...                  0.08902     0.0
2        19.69         21.25  ...                  0.08758     0.0
3        11.42         20.38  ...                  0.17300     0.0
4        20.29         14.34  ...                  0.07678     0.0

[5 rows x 31 columns]

In [123]:
# checking for missing values using info() and isnull()
framed_data.info(), framed_data.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

(None, mean radius                0
 mean texture               0
 mean perimeter             0
 mean area                  0
 mean smoothness            0
 mean compactness           0
 mean concavity             0
 mean concave points        0
 mean symmetry              0
 mean fractal dimension     0
 radius error               0
 texture error              0
 perimeter error            0
 area error                 0
 smoothness error           0
 compactness error          0
 concavity error            0
 concave points error       0
 symmetry error             0
 fractal dimension error    0
 worst radius               0
 worst texture              0
 worst perimeter            0
 worst area                 0
 worst smoothness           0
 worst compactness          0
 worst concavity            0
 worst concave points       0
 worst symmetry             0
 worst fractal dimension    0
 Target                     0
 dtype: int64)

In [124]:
def one_hot(y):
  n = y.max() + 1
  m = len(y)
  one_hot = np.zeros((m, n))
  one_hot[np.arange(m), y] = 1
  return one_hot

In [125]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data_array, target_array, test_size=0.2,random_state=42)

In [126]:
one_hot(y_train[:10]), y_train[:10]

(array([[0., 1.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [1., 0.]]), array([1, 0, 1, 1, 1, 0, 1, 1, 1, 0]))

In [127]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [128]:
X_train.shape, y_train.shape

((455, 30), (455,))

In [129]:
y_train_one_hot = one_hot(y_train)
y_test_one_hot = one_hot(y_train)

In [130]:
# activation functions

def sigmoid(z):
  deno = 1 + np.exp(-z)
  return 1 / deno

def softmax(z):
  exps = np.exp(z)
  sum_exp = np.sum(exps, axis=1, keepdims=True)
  return exps / sum_exp

def tanh(z):
  pos_exp = np.exp(z)
  neg_exp = np.exp(-z)
  num = pos_exp - neg_exp
  deno = pos_exp + neg_exp
  return num / deno

# Logistic Regression Class

In [131]:
class LogisticRegression:
  """Class for the implementation of Logistic Regression"""
  
  def __init__(self, alpha=0.1, n_iterations=1000, activation_function=None):
    self.activation_function = activation_function
    self.alpha = alpha
    self.n_iterations = n_iterations

  def gradient_descent(self, X, y):
    m = len(X)
    features = X.shape[1]
    outputs = len(y[1])

    theta = np.random.randn(features, outputs)

    for iteration in range(self.n_iterations):
      y_prob = self.main_predict(X, theta)

      gradients = 1/m * X.T.dot(y_prob - y)
      theta = theta - self.alpha * gradients
    
    return theta

  def fit(self, X, y):
    X_new = np.c_[np.ones((len(X), 1)), X]
    self.theta = self.gradient_descent(X_new, y)


  def main_predict(self, X, theta):
    if (self.activation_function == 'sigmoid'):
      y_prob = sigmoid(X.dot(theta))

    elif (self.activation_function == 'softmax'):
      y_prob = softmax(X.dot(theta))

    elif (self.activation_function == 'tanh'):
      y_prob = tanh(X.dot(theta))

    return y_prob

  def predict(self, X):
    X_new = np.c_[np.ones((len(X), 1)), X]
    self.prob = self.main_predict(X_new, self.theta)

    y_pred = np.argmax(self.prob, axis=1)
    return y_pred

  def predict_proba(self, X):
    X_new = np.c_[np.ones((len(X), 1)), X]
    self.prob = self.main_predict(X_new, self.theta)

    # zero for negative percentages
    # y_proba = np.array(list(map(lambda x: [max(x[0],0), max(x[1], 0)], self.prob)))
    y_proba = self.prob * 100
    return y_proba


# Sigmoid

In [132]:
# sigmoid
log_reg = LogisticRegression(alpha=0.01, n_iterations=1000,activation_function='sigmoid')
log_reg.fit(X_train, y_train_one_hot)

In [133]:
y_pred = log_reg.predict(X_test)

In [134]:
y_pred.shape, y_test.shape

((114,), (114,))

In [135]:
np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)) ,1)

array([[1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [0,

In [136]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.9473684210526315

# Softmax

In [137]:
log_reg1 = LogisticRegression(alpha=0.1, n_iterations=1000,activation_function='softmax')
log_reg1.fit(X_train, y_train_one_hot)

In [138]:
y_pred2 = log_reg1.predict(X_test)

In [139]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred2)

0.9649122807017544

# Tanh

In [140]:
log_reg1 = LogisticRegression(alpha=0.01, n_iterations=2000,activation_function='tanh')
log_reg1.fit(X_train, y_train_one_hot)

In [141]:
y_pred3 = log_reg1.predict(X_test)

In [142]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred3)

0.9298245614035088

## Percentage

In [143]:
log_reg2 = LogisticRegression(alpha=0.01, n_iterations=2000,activation_function='tanh')
log_reg2.fit(X_train, y_train_one_hot)

In [144]:
# percentage of probability

print(log_reg2.predict_proba(X_test))

[[ 57.02898945  89.80474313]
 [ 99.99711519   9.65634085]
 [ 97.12985487  43.26984395]
 [-16.79496443  99.51922148]
 [-22.86332349  96.47758075]
 [ 99.99889579 -88.3181769 ]
 [ 99.99997098 -21.93373291]
 [ 97.81205497  16.48370873]
 [ -0.75741422  22.55192955]
 [ -4.64120788  95.16659144]
 [ -1.30252507  87.03484018]
 [ 98.75246144  45.59998551]
 [ -3.8169833   92.43746447]
 [ 97.80098006  80.65053661]
 [-22.34608671  83.46994081]
 [ 99.75177795  95.46806231]
 [ 25.13762516  94.96946299]
 [ 15.65032577  99.64905076]
 [ 33.25222637  99.90589506]
 [ 99.99665957   2.72080395]
 [ 73.8117178   71.84015576]
 [-13.60559022  89.55698979]
 [ 99.99972019 -77.33841744]
 [-22.83077347  97.97336421]
 [ -5.15552918  97.64363574]
 [-37.38173944  98.62284594]
 [-15.0541729   94.89334003]
 [ 48.20887653  96.21790317]
 [ -2.6461807   93.37516033]
 [ 99.99096436 -74.72294969]
 [-17.71478339  97.32182268]
 [-34.81386703  93.91293653]
 [ 37.65374615  99.34585914]
 [ 58.4440057   94.77142832]
 [ -5.89213263