In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# importing the breast cancer dataset from sklearn

from sklearn import datasets
dataset = datasets.load_breast_cancer()

In [3]:
# getting the shapes of the arrays

dataset['feature_names'].shape, dataset['data'].shape, dataset['target'].shape

((30,), (569, 30), (569,))

In [4]:
# separating the data, feature names and target label into different arrays

data_array = dataset['data']
feature_names = dataset['feature_names']
target_array = dataset['target']

In [5]:
data_array[:5],target_array[:5]

(array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
         3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
         8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
         3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
         1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, 1.326e+03, 8.474e-02, 7.864e-02,
         8.690e-02, 7.017e-02, 1.812e-01, 5.667e-02, 5.435e-01, 7.339e-01,
         3.398e+00, 7.408e+01, 5.225e-03, 1.308e-02, 1.860e-02, 1.340e-02,
         1.389e-02, 3.532e-03, 2.499e+01, 2.341e+01, 1.588e+02, 1.956e+03,
         1.238e-01, 1.866e-01, 2.416e-01, 1.860e-01, 2.750e-01, 8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, 1.203e+03, 1.096e-01, 1.599e-01,
         1.974e-01, 1.279e-01, 2.069e-01, 5.999e-02, 7.456e-01, 7.869e-01,
         4.585e+00, 9.403e+01, 6.150e-03, 4.006e-02, 3.832e-02, 2.058e-02,
         2.250e-02, 4.5

In [6]:
# concatenating the data array and target array to form the pandas dataframe

new = np.concatenate((data_array.reshape(len(data_array), data_array.shape[1]), target_array.reshape(len(target_array), 1)), 1)
feature_names = np.append(feature_names, 'Target')
feature_names = feature_names[:31]


framed_data = pd.DataFrame(new, columns=feature_names)
framed_data.head()

mean radius  mean texture  ...  worst fractal dimension  Target
0        17.99         10.38  ...                  0.11890     0.0
1        20.57         17.77  ...                  0.08902     0.0
2        19.69         21.25  ...                  0.08758     0.0
3        11.42         20.38  ...                  0.17300     0.0
4        20.29         14.34  ...                  0.07678     0.0

[5 rows x 31 columns]

In [7]:
# checking for missing values using info() and isnull()
framed_data.info(), framed_data.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

(None, mean radius                0
 mean texture               0
 mean perimeter             0
 mean area                  0
 mean smoothness            0
 mean compactness           0
 mean concavity             0
 mean concave points        0
 mean symmetry              0
 mean fractal dimension     0
 radius error               0
 texture error              0
 perimeter error            0
 area error                 0
 smoothness error           0
 compactness error          0
 concavity error            0
 concave points error       0
 symmetry error             0
 fractal dimension error    0
 worst radius               0
 worst texture              0
 worst perimeter            0
 worst area                 0
 worst smoothness           0
 worst compactness          0
 worst concavity            0
 worst concave points       0
 worst symmetry             0
 worst fractal dimension    0
 Target                     0
 dtype: int64)

In [8]:
def one_hot(y):
  n = y.max() + 1
  m = len(y)
  one_hot = np.zeros((m, n))
  one_hot[np.arange(m), y] = 1
  return one_hot

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data_array, target_array, test_size=0.2,random_state=42)

In [10]:
one_hot(y_train[:10]), y_train[:10]

(array([[0., 1.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [1., 0.]]), array([1, 0, 1, 1, 1, 0, 1, 1, 1, 0]))

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
X_train.shape, y_train.shape

((455, 30), (455,))

In [13]:
y_train_one_hot = one_hot(y_train)
y_test_one_hot = one_hot(y_train)

In [14]:
# activation functions

def sigmoid(z):
  deno = 1 + np.exp(-z)
  return 1 / deno

def softmax(z):
  exps = np.exp(z)
  sum_exp = np.sum(exps, axis=1, keepdims=True)
  return exps / sum_exp

def tanh(z):
  pos_exp = np.exp(z)
  neg_exp = np.exp(-z)
  num = pos_exp - neg_exp
  deno = pos_exp + neg_exp
  return num / deno

# Logistic Regression Class

In [15]:
class LogisticRegression:
  """Class for the implementation of Logistic Regression"""
  
  def __init__(self, alpha=0.1, n_iterations=1000, activation_function=None):
    self.activation_function = activation_function
    self.alpha = alpha
    self.n_iterations = n_iterations

  def gradient_descent(self, X, y):
    m = len(X)
    features = X.shape[1]
    outputs = len(y[1])

    theta = np.random.randn(features, outputs)

    for iteration in range(self.n_iterations):
      if (self.activation_function == 'sigmoid'):
        y_prob = sigmoid(X.dot(theta))

      elif (self.activation_function == 'softmax'):
        y_prob = softmax(X.dot(theta))

      elif (self.activation_function == 'tanh'):
        y_prob = tanh(X.dot(theta))

      gradients = 1/m * X.T.dot(y_prob - y)
      theta = theta - self.alpha * gradients
    
    return theta

  def fit(self, X, y):
    X_new = np.c_[np.ones((len(X), 1)), X]
    self.theta = self.gradient_descent(X_new, y)


  def main_predict(self, X):
    X_new = np.c_[np.ones((len(X), 1)), X]
    if (self.activation_function == 'sigmoid'):
      y_prob = sigmoid(X_new.dot(self.theta))

    elif (self.activation_function == 'softmax'):
      y_prob = softmax(X_new.dot(self.theta))

    elif (self.activation_function == 'tanh'):
      y_prob = tanh(X_new.dot(self.theta))

    return y_prob

  def predict(self, X):
    self.prob = self.main_predict(X)

    y_pred = np.argmax(self.prob, axis=1)
    return y_pred

  def predict_proba(self, X):
    self.prob = self.main_predict(X)

    # zero for negative percentages
    # y_proba = np.array(list(map(lambda x: [max(x[0],0), max(x[1], 0)], self.prob)))
    y_proba = self.prob * 100
    return y_proba


# Sigmoid

In [16]:
# sigmoid
log_reg = LogisticRegression(alpha=0.01, n_iterations=1000,activation_function='sigmoid')
log_reg.fit(X_train, y_train_one_hot)

In [17]:
y_pred = log_reg.predict(X_test)

In [18]:
y_pred.shape, y_test.shape

((114,), (114,))

In [19]:
np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)) ,1)

array([[1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 1],
       [0,

In [20]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.9385964912280702

# Softmax

In [21]:
log_reg1 = LogisticRegression(alpha=0.1, n_iterations=1000,activation_function='softmax')
log_reg1.fit(X_train, y_train_one_hot)

In [22]:
y_pred2 = log_reg1.predict(X_test)

In [23]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred2)

0.9824561403508771

# Tanh

In [24]:
log_reg1 = LogisticRegression(alpha=0.01, n_iterations=2000,activation_function='tanh')
log_reg1.fit(X_train, y_train_one_hot)

In [25]:
y_pred3 = log_reg1.predict(X_test)

In [26]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred3)

0.9473684210526315

## Percentage

In [27]:
log_reg2 = LogisticRegression(alpha=0.01, n_iterations=2000,activation_function='tanh')
log_reg2.fit(X_train, y_train_one_hot)

In [28]:
# percentage of probability

print(log_reg2.predict_proba(X_test))

[[ 55.50545091  90.84370624]
 [ 99.04664479 -24.85042542]
 [ 96.42221863   1.95142176]
 [-15.87682101  99.31014848]
 [ -9.14940439  99.89388679]
 [ 99.99358021 -65.4789313 ]
 [ 99.99564281 -69.57164034]
 [ 96.7153118   58.35253504]
 [ 63.52144313  70.90202669]
 [ -3.94657452  99.12160189]
 [  1.18503427  79.02402297]
 [ 87.93518286  73.29910172]
 [-36.04888179  91.69361107]
 [ 99.47954584  88.15881759]
 [ 14.41094744  94.37154278]
 [ 99.96106255  34.4007585 ]
 [  2.10221433  97.6463227 ]
 [  0.79941487  99.96617557]
 [-47.93273087  99.95118881]
 [ 99.8998033  -41.16803381]
 [ 75.66147706  84.36065056]
 [ 25.66567514  96.35188295]
 [ 99.94342764 -66.82710442]
 [-11.20999048  99.54492527]
 [ 39.24003533  98.9030499 ]
 [ 92.17907412  99.8249208 ]
 [-17.38246774  93.71622458]
 [-21.06365373  96.94678665]
 [-26.00984267  91.25128686]
 [ 96.28057293   2.75596046]
 [ 10.45627071  85.42674108]
 [ -9.98763059  98.41652482]
 [ 42.36251975  99.79209149]
 [ 28.81947563  93.0379048 ]
 [-25.27654115