In [58]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [59]:
df = pd.read_csv('Data.csv')

In [60]:
df.head()

Sample code number  Clump Thickness  ...  Mitoses  Class
0             1000025                5  ...        1      2
1             1002945                5  ...        1      2
2             1015425                3  ...        1      2
3             1016277                6  ...        1      2
4             1017023                4  ...        1      2

[5 rows x 11 columns]

In [61]:
df = df.drop('Sample code number', axis=1)

In [62]:
df

Clump Thickness  Uniformity of Cell Size  ...  Mitoses  Class
0                  5                        1  ...        1      2
1                  5                        4  ...        1      2
2                  3                        1  ...        1      2
3                  6                        8  ...        1      2
4                  4                        1  ...        1      2
..               ...                      ...  ...      ...    ...
678                3                        1  ...        1      2
679                2                        1  ...        1      2
680                5                       10  ...        2      4
681                4                        8  ...        1      4
682                4                        8  ...        1      4

[683 rows x 10 columns]

In [63]:
df.describe()

Clump Thickness  Uniformity of Cell Size  ...     Mitoses       Class
count       683.000000               683.000000  ...  683.000000  683.000000
mean          4.442167                 3.150805  ...    1.603221    2.699854
std           2.820761                 3.065145  ...    1.732674    0.954592
min           1.000000                 1.000000  ...    1.000000    2.000000
25%           2.000000                 1.000000  ...    1.000000    2.000000
50%           4.000000                 1.000000  ...    1.000000    2.000000
75%           6.000000                 5.000000  ...    1.000000    4.000000
max          10.000000                10.000000  ...   10.000000    4.000000

[8 rows x 10 columns]

In [64]:
# check for missing values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 683 entries, 0 to 682
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Clump Thickness              683 non-null    int64
 1   Uniformity of Cell Size      683 non-null    int64
 2   Uniformity of Cell Shape     683 non-null    int64
 3   Marginal Adhesion            683 non-null    int64
 4   Single Epithelial Cell Size  683 non-null    int64
 5   Bare Nuclei                  683 non-null    int64
 6   Bland Chromatin              683 non-null    int64
 7   Normal Nucleoli              683 non-null    int64
 8   Mitoses                      683 non-null    int64
 9   Class                        683 non-null    int64
dtypes: int64(10)
memory usage: 53.5 KB


In [65]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [66]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [67]:
X[:10], y[:10]

(array([[ 5,  1,  1,  1,  2,  1,  3,  1,  1],
        [ 5,  4,  4,  5,  7, 10,  3,  2,  1],
        [ 3,  1,  1,  1,  2,  2,  3,  1,  1],
        [ 6,  8,  8,  1,  3,  4,  3,  7,  1],
        [ 4,  1,  1,  3,  2,  1,  3,  1,  1],
        [ 8, 10, 10,  8,  7, 10,  9,  7,  1],
        [ 1,  1,  1,  1,  2, 10,  3,  1,  1],
        [ 2,  1,  2,  1,  2,  1,  3,  1,  1],
        [ 2,  1,  1,  1,  2,  1,  1,  1,  5],
        [ 4,  2,  1,  1,  2,  1,  2,  1,  1]]),
 array([2, 2, 2, 2, 2, 4, 2, 2, 2, 2]))

In [68]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [69]:
X_train[:5], y_train[:5]

(array([[ 1,  1,  1,  1,  2,  1,  3,  1,  1],
        [ 1,  1,  1,  1,  2,  1,  2,  1,  1],
        [ 5,  7,  9,  8,  6, 10,  8, 10,  1],
        [10,  5,  7,  4,  4, 10,  8,  9,  1],
        [ 3,  2,  2,  3,  2,  3,  3,  1,  1]]), array([2, 2, 4, 4, 2]))

In [70]:
X_test[:5], y_test[:5]

(array([[ 7,  4,  5, 10,  2, 10,  3,  8,  2],
        [ 2,  1,  1,  2,  2,  1,  3,  1,  1],
        [ 3,  1,  1,  1,  2,  1,  3,  1,  1],
        [ 5,  1,  1,  1,  2,  1,  3,  1,  1],
        [10,  5,  5,  3,  6,  7,  7, 10,  1]]), array([4, 2, 2, 2, 4]))

In [71]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [72]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [73]:
y_pred = knn.predict(X_test)

In [74]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import cross_val_score

In [75]:
print(confusion_matrix(y_test, y_pred))

[[139   4]
 [  4  58]]


In [76]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           2       0.97      0.97      0.97       143
           4       0.94      0.94      0.94        62

    accuracy                           0.96       205
   macro avg       0.95      0.95      0.95       205
weighted avg       0.96      0.96      0.96       205



In [77]:
print(accuracy_score(y_test, y_pred))

0.9609756097560975


In [78]:
# finding the optimal value of n_neighbor for knn

from sklearn.model_selection import GridSearchCV

k_vals = list(range(1,20))
k_params = {'n_neighbors' : k_vals}

knn = KNeighborsClassifier()
knn_classifier = GridSearchCV(knn, k_params, cv = 10, scoring = 'accuracy')
knn_classifier.fit(X,y)

GridSearchCV(cv=10, error_score=nan,
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=5, p=2,
                                            weights='uniform'),
             iid='deprecated', n_jobs=None,
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                         13, 14, 15, 16, 17, 18, 19]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy', verbose=0)

In [79]:
knn_classifier.best_params_, knn_classifier.best_score_

({'n_neighbors': 5}, 0.9722719522591646)

In [80]:
knn_classifier.best_estimator_

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [81]:
KNN = KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')
KNN.fit(X_train, y_train)

y_pred = KNN.predict(X_test)

In [82]:
print(confusion_matrix(y_test, y_pred))

[[141   2]
 [  3  59]]


In [83]:
print(accuracy_score(y_test, y_pred))

0.975609756097561


In [84]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           2       0.98      0.99      0.98       143
           4       0.97      0.95      0.96        62

    accuracy                           0.98       205
   macro avg       0.97      0.97      0.97       205
weighted avg       0.98      0.98      0.98       205

